# Generated by Django 2.2.27 on 2022-12-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tweet_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300)),
                ('answer', models.TextField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
